#! /bin/sh
#symbolic link test

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d web code media graphics misc 

#wallpaper
feh --bg-fill ~/Pictures/wallpapers/board.png
xrandr --output Virtual1 --mode 1366x768 

#launch polybar
bash ~/.config/polybar/launch.sh  &
#bash ~/.config/polybar/polybar/launch.sh &

#dunst
dunst -conf ~/.config/dust/dunstrc &

picom &

#double border
~/.config/bspwm/bin/bspborder

bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
