#! /bin/sh
#symbolic link test

pgrep -x sxhkd > /dev/null || sxhkd &

#cursor
xsetroot -cursor_name left_ptr &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d web code media graphics misc 

#wallpaper
#feh --bg-fill ~/Pictures/wallpapers/board.png
#feh --bg-fill ~/Pictures/wallpapers/board.png
#feh --bg-fill ~/Pictures/wallpapers/board.png
#feh --bg-fill ~/Pictures/wallpapers/board.png
feh --bg-fill ~/Pictures/Wall/girl.png

#resolution
xrandr --output Virtual1 --mode 1366x768 

#launch polybar
sh ~/.config/polybar/grayblocks/launch.sh  &

#dunst
dunst -conf ~/.config/dust/dunstrc &

#mpd
mpd &

picom &

#double border
sh ~/.config/bspwm/bin/bspborder

bspc config border_width         0
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#border
bspc config focused_border_color "#FABD2F"
bspc config normal_border_color "#928374"
bspc config active_border_color "#83A598"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
